services:
  - type: web
    name: laptop-inventory
    env: docker
    plan: free
    region: ohio
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://dpg-d27vlip5pdvs7381i7q0-a.ohio-postgres.render.com:5432/laptop_inventory
      - key: SPRING_DATASOURCE_USERNAME
        value: r3tha
      - key: SPRING_DATASOURCE_PASSWORD
        value: YOUR_DB_PASSWORD_HERE
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update